---
image:
  file: .devcontainer/Dockerfile 
ports:
  - port: 80
  - port: 3306
  - port: 443
tasks:
  - name: Setup
    env:
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: rootmysql
      MYSQL_USER_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      WORDPRESS_TITLE: wordpress
      WORDPRESS_USER: karneaud
      WORDPRESS_USER_EMAIL: admin@email.local
    command: >
      ./.devcontainer/postCreateCommand.sh
